spring:
  application:
    name: price_monitoring_system

#  main:
#    web-application-type: none

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 15
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        connection:
          provider_disables_autocommit: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://db:5432/price_monitoring_db?options=-c%20timezone=UTC
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: price-monitoring-system-hikari-pool

  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
    enabled: true

scraping:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  timeout: 5000

telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}

#logging:
#  level:
#    org.telegram.telegrambots: DEBUG
